version: '3.8'

services:
  app:
    image: jeogiyo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY=${API_KEY}
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: jeogiyo_psql
    image: postgres:14-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: jeogiyo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami/redis
      - /home/ubuntu/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app_network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge