spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  data:
    redis:
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

jwt:
  secret:
    expiration-time: ${JWT_EXPIRATION_TIME}
    key: ${JWT_SECRET_KEY}

api:
  key: ${API_KEY}