spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

jwt:
  secret:
    expiration-time: 3600000
    key: ${LOCAL_JWT_SECRET_KEY}

api:
  key: ${YOUR_API_KEY}